### ISSUE TITLE
please help trigger tag with events and contexts

### ISSUE THREAD

**Issue by paulVu** [daiangan/manychat-dialogflow-connector#1]
Hello Daiangan,
Thank your build this one. 
I'm not a developer, So Please help us to build move with this one. 

1. Manychat can use tag to trigger event on dialgoflow. 

- That help flow on manychat can detect exacly what user talking about. 

2. Dialogflow can response to update the tag via context.
- That help less training on Dialogflow.

**Comment by daiangan** [comment]
Hi @paulVu , thanks for the feature requests. You can achieve those things with ManyChat itself.
For number one you can use a Rule. Go to Automation - Rules and then select "Tag applied" as your Trigger, then on the right side go and select the flow you want to start.
For the second one, remember that the context is sent to Dialogflow manually from the app, so you already have the context in ManyChat and can use it to update a tag as you want using the flow builder tools.

Please let me know if this makes sense to you.

**Comment by paulVu** [comment]
You are right!. I used "tag" and "custom user field", that work on flow builder tools.
